export default [
    {text: "USD/EUR", value: "USD"},
    {text: "EUR/USD", value: "EUR"},
    {text: "TRY/EUR", value: "TRY"},
    {text: "AUD/EUR", value: "AUD"},
    {text: "CNY/EUR", value: "CNY"},
    {text: "HKD/EUR", value: "HKD"},
    {text: "INR/EUR", value: "INR"},
    {text: "JPY/EUR", value: "JPY"},
    {text: "AED/EUR", value: "AED"},
    {text: "BTC/EUR", value: "BTC"},
    {text: "ETH/EUR", value: "ETH"},
    {text: "XRP/EUR", value: "XRP"},
    {text: "LTC/EUR", value: "LTC"},
    {text: "GOOG/EUR", value: "GOOG"},
    {text: "MSFT/EUR", value: "MSFT"},
    {text: "AAPL/EUR", value: "AAPL"},
    {text: "AMZN/EUR", value: "AMZN"},
    {text: "FB/EUR", value: "FB"},
];